/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'GreenCertificateSBT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GreenCertificateSBT__factory>
getContractFactory(name: 'SAL1155', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SAL1155__factory>
getContractFactory(name: 'SALMarketplace', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SALMarketplace__factory>

  getContractAt(name: 'GreenCertificateSBT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GreenCertificateSBT>
getContractAt(name: 'SAL1155', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SAL1155>
getContractAt(name: 'SALMarketplace', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SALMarketplace>

  deployContract(name: 'GreenCertificateSBT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GreenCertificateSBT>
deployContract(name: 'SAL1155', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SAL1155>
deployContract(name: 'SALMarketplace', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SALMarketplace>

  deployContract(name: 'GreenCertificateSBT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GreenCertificateSBT>
deployContract(name: 'SAL1155', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SAL1155>
deployContract(name: 'SALMarketplace', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SALMarketplace>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  