/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SAL1155Interface extends Interface {
    getFunction(nameOrSignature: "balanceOf" | "balanceOfBatch" | "blacklistProject" | "burnSAL" | "isApprovedForAll" | "lockMarketplace" | "marketplace" | "marketplaceLocked" | "mintSAL" | "owner" | "pause" | "paused" | "projectBlacklist" | "releaseBlacklistedSAL" | "renounceOwnership" | "safeBatchTransferFrom" | "safeTransferFrom" | "setApprovalForAll" | "setMarketplace" | "setTokenURI" | "supportsInterface" | "transferOwnership" | "unblacklistProject" | "unpause" | "uri"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ApprovalForAll" | "MarketplaceLocked" | "MarketplaceUpdated" | "OwnershipTransferred" | "Paused" | "ProjectBlacklisted" | "ProjectUnblacklisted" | "SALBurned" | "SALMinted" | "TokenURIUpdated" | "TransferBatch" | "TransferSingle" | "URI" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOfBatch', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'blacklistProject', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'burnSAL', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'lockMarketplace', values?: undefined): string;
encodeFunctionData(functionFragment: 'marketplace', values?: undefined): string;
encodeFunctionData(functionFragment: 'marketplaceLocked', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintSAL', values: [AddressLike, BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'projectBlacklist', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'releaseBlacklistedSAL', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'safeBatchTransferFrom', values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setMarketplace', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTokenURI', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unblacklistProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'uri', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOfBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'blacklistProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burnSAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockMarketplace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketplace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketplaceLocked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintSAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projectBlacklist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseBlacklistedSAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeBatchTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMarketplace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unblacklistProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uri', data: BytesLike): Result;
  }

  
    export namespace ApprovalForAllEvent {
      export type InputTuple = [account: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [account: string, operator: string, approved: boolean];
      export interface OutputObject {account: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketplaceLockedEvent {
      export type InputTuple = [marketplace: AddressLike];
      export type OutputTuple = [marketplace: string];
      export interface OutputObject {marketplace: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketplaceUpdatedEvent {
      export type InputTuple = [oldMarketplace: AddressLike, newMarketplace: AddressLike];
      export type OutputTuple = [oldMarketplace: string, newMarketplace: string];
      export interface OutputObject {oldMarketplace: string, newMarketplace: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectBlacklistedEvent {
      export type InputTuple = [projectId: BigNumberish, reason: string];
      export type OutputTuple = [projectId: bigint, reason: string];
      export interface OutputObject {projectId: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectUnblacklistedEvent {
      export type InputTuple = [projectId: BigNumberish];
      export type OutputTuple = [projectId: bigint];
      export interface OutputObject {projectId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SALBurnedEvent {
      export type InputTuple = [from: AddressLike, projectId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [from: string, projectId: bigint, amount: bigint];
      export interface OutputObject {from: string, projectId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SALMintedEvent {
      export type InputTuple = [to: AddressLike, projectId: BigNumberish, amount: BigNumberish, tokenURI: string];
      export type OutputTuple = [to: string, projectId: bigint, amount: bigint, tokenURI: string];
      export interface OutputObject {to: string, projectId: bigint, amount: bigint, tokenURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenURIUpdatedEvent {
      export type InputTuple = [projectId: BigNumberish, tokenURI: string];
      export type OutputTuple = [projectId: bigint, tokenURI: string];
      export interface OutputObject {projectId: bigint, tokenURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferBatchEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[]];
      export type OutputTuple = [operator: string, from: string, to: string, ids: bigint[], values: bigint[]];
      export interface OutputObject {operator: string, from: string, to: string, ids: bigint[], values: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferSingleEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish];
      export type OutputTuple = [operator: string, from: string, to: string, id: bigint, value: bigint];
      export interface OutputObject {operator: string, from: string, to: string, id: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace URIEvent {
      export type InputTuple = [value: string, id: BigNumberish];
      export type OutputTuple = [value: string, id: bigint];
      export interface OutputObject {value: string, id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SAL1155 extends BaseContract {
    
    connect(runner?: ContractRunner | null): SAL1155;
    waitForDeployment(): Promise<this>;

    interface: SAL1155Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balanceOf: TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    balanceOfBatch: TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >
    

    
    blacklistProject: TypedContractMethod<
      [projectId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    burnSAL: TypedContractMethod<
      [from: AddressLike, projectId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    lockMarketplace: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    marketplace: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    marketplaceLocked: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    mintSAL: TypedContractMethod<
      [to: AddressLike, projectId: BigNumberish, amount: BigNumberish, tokenURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    projectBlacklist: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    releaseBlacklistedSAL: TypedContractMethod<
      [to: AddressLike, projectId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    safeBatchTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    safeTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setMarketplace: TypedContractMethod<
      [_marketplace: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTokenURI: TypedContractMethod<
      [projectId: BigNumberish, tokenURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unblacklistProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    uri: TypedContractMethod<
      [projectId: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOfBatch'): TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'blacklistProject'): TypedContractMethod<
      [projectId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'burnSAL'): TypedContractMethod<
      [from: AddressLike, projectId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lockMarketplace'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'marketplace'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'marketplaceLocked'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mintSAL'): TypedContractMethod<
      [to: AddressLike, projectId: BigNumberish, amount: BigNumberish, tokenURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'projectBlacklist'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'releaseBlacklistedSAL'): TypedContractMethod<
      [to: AddressLike, projectId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeBatchTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMarketplace'): TypedContractMethod<
      [_marketplace: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTokenURI'): TypedContractMethod<
      [projectId: BigNumberish, tokenURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unblacklistProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'uri'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'MarketplaceLocked'): TypedContractEvent<MarketplaceLockedEvent.InputTuple, MarketplaceLockedEvent.OutputTuple, MarketplaceLockedEvent.OutputObject>;
getEvent(key: 'MarketplaceUpdated'): TypedContractEvent<MarketplaceUpdatedEvent.InputTuple, MarketplaceUpdatedEvent.OutputTuple, MarketplaceUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'ProjectBlacklisted'): TypedContractEvent<ProjectBlacklistedEvent.InputTuple, ProjectBlacklistedEvent.OutputTuple, ProjectBlacklistedEvent.OutputObject>;
getEvent(key: 'ProjectUnblacklisted'): TypedContractEvent<ProjectUnblacklistedEvent.InputTuple, ProjectUnblacklistedEvent.OutputTuple, ProjectUnblacklistedEvent.OutputObject>;
getEvent(key: 'SALBurned'): TypedContractEvent<SALBurnedEvent.InputTuple, SALBurnedEvent.OutputTuple, SALBurnedEvent.OutputObject>;
getEvent(key: 'SALMinted'): TypedContractEvent<SALMintedEvent.InputTuple, SALMintedEvent.OutputTuple, SALMintedEvent.OutputObject>;
getEvent(key: 'TokenURIUpdated'): TypedContractEvent<TokenURIUpdatedEvent.InputTuple, TokenURIUpdatedEvent.OutputTuple, TokenURIUpdatedEvent.OutputObject>;
getEvent(key: 'TransferBatch'): TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
getEvent(key: 'TransferSingle'): TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
getEvent(key: 'URI'): TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'MarketplaceLocked(address)': TypedContractEvent<MarketplaceLockedEvent.InputTuple, MarketplaceLockedEvent.OutputTuple, MarketplaceLockedEvent.OutputObject>;
      MarketplaceLocked: TypedContractEvent<MarketplaceLockedEvent.InputTuple, MarketplaceLockedEvent.OutputTuple, MarketplaceLockedEvent.OutputObject>;
    

      'MarketplaceUpdated(address,address)': TypedContractEvent<MarketplaceUpdatedEvent.InputTuple, MarketplaceUpdatedEvent.OutputTuple, MarketplaceUpdatedEvent.OutputObject>;
      MarketplaceUpdated: TypedContractEvent<MarketplaceUpdatedEvent.InputTuple, MarketplaceUpdatedEvent.OutputTuple, MarketplaceUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'ProjectBlacklisted(uint256,string)': TypedContractEvent<ProjectBlacklistedEvent.InputTuple, ProjectBlacklistedEvent.OutputTuple, ProjectBlacklistedEvent.OutputObject>;
      ProjectBlacklisted: TypedContractEvent<ProjectBlacklistedEvent.InputTuple, ProjectBlacklistedEvent.OutputTuple, ProjectBlacklistedEvent.OutputObject>;
    

      'ProjectUnblacklisted(uint256)': TypedContractEvent<ProjectUnblacklistedEvent.InputTuple, ProjectUnblacklistedEvent.OutputTuple, ProjectUnblacklistedEvent.OutputObject>;
      ProjectUnblacklisted: TypedContractEvent<ProjectUnblacklistedEvent.InputTuple, ProjectUnblacklistedEvent.OutputTuple, ProjectUnblacklistedEvent.OutputObject>;
    

      'SALBurned(address,uint256,uint256)': TypedContractEvent<SALBurnedEvent.InputTuple, SALBurnedEvent.OutputTuple, SALBurnedEvent.OutputObject>;
      SALBurned: TypedContractEvent<SALBurnedEvent.InputTuple, SALBurnedEvent.OutputTuple, SALBurnedEvent.OutputObject>;
    

      'SALMinted(address,uint256,uint256,string)': TypedContractEvent<SALMintedEvent.InputTuple, SALMintedEvent.OutputTuple, SALMintedEvent.OutputObject>;
      SALMinted: TypedContractEvent<SALMintedEvent.InputTuple, SALMintedEvent.OutputTuple, SALMintedEvent.OutputObject>;
    

      'TokenURIUpdated(uint256,string)': TypedContractEvent<TokenURIUpdatedEvent.InputTuple, TokenURIUpdatedEvent.OutputTuple, TokenURIUpdatedEvent.OutputObject>;
      TokenURIUpdated: TypedContractEvent<TokenURIUpdatedEvent.InputTuple, TokenURIUpdatedEvent.OutputTuple, TokenURIUpdatedEvent.OutputObject>;
    

      'TransferBatch(address,address,address,uint256[],uint256[])': TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
      TransferBatch: TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
    

      'TransferSingle(address,address,address,uint256,uint256)': TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
      TransferSingle: TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
    

      'URI(string,uint256)': TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
      URI: TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }