/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SALMarketplaceInterface extends Interface {
    getFunction(nameOrSignature: "CERTIFICATE_METADATA_TYPEHASH" | "KG_CO2_PER_SAL" | "MAX_RETIREMENT_PROJECTS" | "addValidator" | "approveAndMintSAL" | "blacklistOwner" | "blacklistProject" | "blacklistedOwners" | "buySAL" | "cancelListing" | "cancelPendingProject" | "certificateAuthorizationDigest" | "certificateMintFee" | "certificateNonces" | "certificateSBT" | "claimTreasury" | "createListing" | "eip712Domain" | "forceCancelListing" | "getProjectValidationSnapshot" | "getValidatorsCount" | "hasVotedOnProject" | "isValidator" | "listingApprovalVotes" | "listings" | "maxPrice" | "metadataSigner" | "minPrice" | "nextListingId" | "nextProjectId" | "onERC1155BatchReceived" | "onERC1155Received" | "owner" | "pause" | "paused" | "platformFeeBps" | "projectApprovalQuorum" | "projectEligibleValidatorCount" | "projectTokenizationFees" | "projectValidatorEligible" | "projects" | "removeValidator" | "renounceOwnership" | "retireSAL" | "salToken" | "salTokenizationFeePerSAL" | "sellerBalances" | "submitProject" | "supportsInterface" | "tokenizationFeeRefundBalances" | "transferOwnership" | "treasuryBalance" | "unblacklistOwner" | "unblacklistProject" | "unpause" | "updateCertificateMintFee" | "updateMetadataSigner" | "updatePlatformFee" | "updatePriceRange" | "updateSALTokenizationFeePerSAL" | "validators" | "voteOnProject" | "withdrawProceeds" | "withdrawTokenizationFeeRefund"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CertificateMintFeeCollected" | "CertificateMintFeeUpdated" | "EIP712DomainChanged" | "ListingCancelled" | "ListingCreated" | "MetadataSignerUpdated" | "MultiProjectSALRetired" | "OwnerBlacklisted" | "OwnerUnblacklisted" | "OwnershipTransferred" | "Paused" | "PendingProjectCancelled" | "ProjectApprovalVoted" | "ProjectApproved" | "ProjectBlacklisted" | "ProjectSubmitted" | "ProjectUnblacklisted" | "ProjectValidatorSnapshot" | "SALPurchased" | "SALRetired" | "SALTokenizationFeeUpdated" | "TokenizationDepositReceived" | "TokenizationFeeCollected" | "TokenizationFeeRefundCredited" | "TokenizationFeeRefundWithdrawn" | "TreasuryClaimed" | "Unpaused" | "ValidatorAdded" | "ValidatorRemoved"): EventFragment;

    encodeFunctionData(functionFragment: 'CERTIFICATE_METADATA_TYPEHASH', values?: undefined): string;
encodeFunctionData(functionFragment: 'KG_CO2_PER_SAL', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_RETIREMENT_PROJECTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'addValidator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'approveAndMintSAL', values: [BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'blacklistOwner', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'blacklistProject', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'blacklistedOwners', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'buySAL', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelListing', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelPendingProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'certificateAuthorizationDigest', values: [AddressLike, BigNumberish[], BigNumberish[], string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'certificateMintFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'certificateNonces', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'certificateSBT', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimTreasury', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createListing', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'eip712Domain', values?: undefined): string;
encodeFunctionData(functionFragment: 'forceCancelListing', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProjectValidationSnapshot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getValidatorsCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasVotedOnProject', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isValidator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'listingApprovalVotes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'listings', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'maxPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'metadataSigner', values?: undefined): string;
encodeFunctionData(functionFragment: 'minPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextListingId', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextProjectId', values?: undefined): string;
encodeFunctionData(functionFragment: 'onERC1155BatchReceived', values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'onERC1155Received', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'platformFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'projectApprovalQuorum', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'projectEligibleValidatorCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'projectTokenizationFees', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'projectValidatorEligible', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'projects', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeValidator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'retireSAL', values: [BigNumberish[], BigNumberish[], string, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'salToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'salTokenizationFeePerSAL', values?: undefined): string;
encodeFunctionData(functionFragment: 'sellerBalances', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'submitProject', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'tokenizationFeeRefundBalances', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasuryBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'unblacklistOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unblacklistProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateCertificateMintFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateMetadataSigner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePlatformFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updatePriceRange', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateSALTokenizationFeePerSAL', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'validators', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'voteOnProject', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'withdrawProceeds', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawTokenizationFeeRefund', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'CERTIFICATE_METADATA_TYPEHASH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'KG_CO2_PER_SAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_RETIREMENT_PROJECTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addValidator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveAndMintSAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'blacklistOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'blacklistProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'blacklistedOwners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buySAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelPendingProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'certificateAuthorizationDigest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'certificateMintFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'certificateNonces', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'certificateSBT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eip712Domain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'forceCancelListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProjectValidationSnapshot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getValidatorsCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVotedOnProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isValidator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listingApprovalVotes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'metadataSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextListingId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextProjectId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC1155BatchReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC1155Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projectApprovalQuorum', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projectEligibleValidatorCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projectTokenizationFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projectValidatorEligible', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projects', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeValidator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'retireSAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'salToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'salTokenizationFeePerSAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sellerBalances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenizationFeeRefundBalances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasuryBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unblacklistOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unblacklistProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCertificateMintFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateMetadataSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePlatformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePriceRange', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateSALTokenizationFeePerSAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validators', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteOnProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawProceeds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawTokenizationFeeRefund', data: BytesLike): Result;
  }

  
    export namespace CertificateMintFeeCollectedEvent {
      export type InputTuple = [retirer: AddressLike, projectId: BigNumberish, certificateTokenId: BigNumberish, feeAmount: BigNumberish];
      export type OutputTuple = [retirer: string, projectId: bigint, certificateTokenId: bigint, feeAmount: bigint];
      export interface OutputObject {retirer: string, projectId: bigint, certificateTokenId: bigint, feeAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CertificateMintFeeUpdatedEvent {
      export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
      export type OutputTuple = [oldFee: bigint, newFee: bigint];
      export interface OutputObject {oldFee: bigint, newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EIP712DomainChangedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ListingCancelledEvent {
      export type InputTuple = [listingId: BigNumberish];
      export type OutputTuple = [listingId: bigint];
      export interface OutputObject {listingId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ListingCreatedEvent {
      export type InputTuple = [listingId: BigNumberish, projectId: BigNumberish, seller: AddressLike, amount: BigNumberish, pricePerUnit: BigNumberish];
      export type OutputTuple = [listingId: bigint, projectId: bigint, seller: string, amount: bigint, pricePerUnit: bigint];
      export interface OutputObject {listingId: bigint, projectId: bigint, seller: string, amount: bigint, pricePerUnit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MetadataSignerUpdatedEvent {
      export type InputTuple = [oldSigner: AddressLike, newSigner: AddressLike];
      export type OutputTuple = [oldSigner: string, newSigner: string];
      export interface OutputObject {oldSigner: string, newSigner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MultiProjectSALRetiredEvent {
      export type InputTuple = [retirer: AddressLike, certificateTokenId: BigNumberish, projectIds: BigNumberish[], salAmounts: BigNumberish[], totalSALAmount: BigNumberish, totalCO2Kg: BigNumberish];
      export type OutputTuple = [retirer: string, certificateTokenId: bigint, projectIds: bigint[], salAmounts: bigint[], totalSALAmount: bigint, totalCO2Kg: bigint];
      export interface OutputObject {retirer: string, certificateTokenId: bigint, projectIds: bigint[], salAmounts: bigint[], totalSALAmount: bigint, totalCO2Kg: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerBlacklistedEvent {
      export type InputTuple = [account: AddressLike, reason: string];
      export type OutputTuple = [account: string, reason: string];
      export interface OutputObject {account: string, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerUnblacklistedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PendingProjectCancelledEvent {
      export type InputTuple = [projectId: BigNumberish, owner: AddressLike, refundAmount: BigNumberish];
      export type OutputTuple = [projectId: bigint, owner: string, refundAmount: bigint];
      export interface OutputObject {projectId: bigint, owner: string, refundAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectApprovalVotedEvent {
      export type InputTuple = [projectId: BigNumberish, validator: AddressLike, approved: boolean];
      export type OutputTuple = [projectId: bigint, validator: string, approved: boolean];
      export interface OutputObject {projectId: bigint, validator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectApprovedEvent {
      export type InputTuple = [projectId: BigNumberish, approvedBy: AddressLike, approvedCO2Kg: BigNumberish, salAmount: BigNumberish];
      export type OutputTuple = [projectId: bigint, approvedBy: string, approvedCO2Kg: bigint, salAmount: bigint];
      export interface OutputObject {projectId: bigint, approvedBy: string, approvedCO2Kg: bigint, salAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectBlacklistedEvent {
      export type InputTuple = [projectId: BigNumberish, reason: string];
      export type OutputTuple = [projectId: bigint, reason: string];
      export interface OutputObject {projectId: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectSubmittedEvent {
      export type InputTuple = [projectId: BigNumberish, owner: AddressLike, projectURI: string, proposedCO2Kg: BigNumberish];
      export type OutputTuple = [projectId: bigint, owner: string, projectURI: string, proposedCO2Kg: bigint];
      export interface OutputObject {projectId: bigint, owner: string, projectURI: string, proposedCO2Kg: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectUnblacklistedEvent {
      export type InputTuple = [projectId: BigNumberish];
      export type OutputTuple = [projectId: bigint];
      export interface OutputObject {projectId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectValidatorSnapshotEvent {
      export type InputTuple = [projectId: BigNumberish, eligibleValidatorCount: BigNumberish, approvalQuorum: BigNumberish];
      export type OutputTuple = [projectId: bigint, eligibleValidatorCount: bigint, approvalQuorum: bigint];
      export interface OutputObject {projectId: bigint, eligibleValidatorCount: bigint, approvalQuorum: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SALPurchasedEvent {
      export type InputTuple = [listingId: BigNumberish, buyer: AddressLike, salAmount: BigNumberish, totalPrice: BigNumberish, feePaid: BigNumberish];
      export type OutputTuple = [listingId: bigint, buyer: string, salAmount: bigint, totalPrice: bigint, feePaid: bigint];
      export interface OutputObject {listingId: bigint, buyer: string, salAmount: bigint, totalPrice: bigint, feePaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SALRetiredEvent {
      export type InputTuple = [retirer: AddressLike, projectId: BigNumberish, salAmount: BigNumberish, co2Kg: BigNumberish, certificateTokenId: BigNumberish];
      export type OutputTuple = [retirer: string, projectId: bigint, salAmount: bigint, co2Kg: bigint, certificateTokenId: bigint];
      export interface OutputObject {retirer: string, projectId: bigint, salAmount: bigint, co2Kg: bigint, certificateTokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SALTokenizationFeeUpdatedEvent {
      export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
      export type OutputTuple = [oldFee: bigint, newFee: bigint];
      export interface OutputObject {oldFee: bigint, newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenizationDepositReceivedEvent {
      export type InputTuple = [projectId: BigNumberish, owner: AddressLike, maximumSALAmount: BigNumberish, lockedFeePerSAL: BigNumberish, depositAmount: BigNumberish];
      export type OutputTuple = [projectId: bigint, owner: string, maximumSALAmount: bigint, lockedFeePerSAL: bigint, depositAmount: bigint];
      export interface OutputObject {projectId: bigint, owner: string, maximumSALAmount: bigint, lockedFeePerSAL: bigint, depositAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenizationFeeCollectedEvent {
      export type InputTuple = [projectId: BigNumberish, owner: AddressLike, salAmount: BigNumberish, feeAmount: BigNumberish];
      export type OutputTuple = [projectId: bigint, owner: string, salAmount: bigint, feeAmount: bigint];
      export interface OutputObject {projectId: bigint, owner: string, salAmount: bigint, feeAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenizationFeeRefundCreditedEvent {
      export type InputTuple = [projectId: BigNumberish, owner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [projectId: bigint, owner: string, amount: bigint];
      export interface OutputObject {projectId: bigint, owner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenizationFeeRefundWithdrawnEvent {
      export type InputTuple = [owner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [owner: string, amount: bigint];
      export interface OutputObject {owner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryClaimedEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidatorAddedEvent {
      export type InputTuple = [validator: AddressLike];
      export type OutputTuple = [validator: string];
      export interface OutputObject {validator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidatorRemovedEvent {
      export type InputTuple = [validator: AddressLike];
      export type OutputTuple = [validator: string];
      export interface OutputObject {validator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SALMarketplace extends BaseContract {
    
    connect(runner?: ContractRunner | null): SALMarketplace;
    waitForDeployment(): Promise<this>;

    interface: SALMarketplaceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CERTIFICATE_METADATA_TYPEHASH: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    KG_CO2_PER_SAL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_RETIREMENT_PROJECTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addValidator: TypedContractMethod<
      [validator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    approveAndMintSAL: TypedContractMethod<
      [projectId: BigNumberish, approvedCO2Kg: BigNumberish, tokenURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    blacklistOwner: TypedContractMethod<
      [account: AddressLike, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    blacklistProject: TypedContractMethod<
      [projectId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    blacklistedOwners: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    buySAL: TypedContractMethod<
      [listingId: BigNumberish, salAmount: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    cancelListing: TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelPendingProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    certificateAuthorizationDigest: TypedContractMethod<
      [retirer: AddressLike, projectIds: BigNumberish[], salAmounts: BigNumberish[], certificateURI: string, nonce: BigNumberish, deadline: BigNumberish, ],
      [string],
      'view'
    >
    

    
    certificateMintFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    certificateNonces: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    certificateSBT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    claimTreasury: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createListing: TypedContractMethod<
      [projectId: BigNumberish, amount: BigNumberish, pricePerUnit: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    eip712Domain: TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >
    

    
    forceCancelListing: TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getProjectValidationSnapshot: TypedContractMethod<
      [projectId: BigNumberish, ],
      [[bigint, bigint] & {eligibleValidatorCount: bigint, approvalQuorum: bigint }],
      'view'
    >
    

    
    getValidatorsCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    hasVotedOnProject: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isValidator: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    listingApprovalVotes: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    listings: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, bigint, bigint, boolean, bigint] & {listingId: bigint, projectId: bigint, seller: string, amount: bigint, pricePerUnit: bigint, active: boolean, createdAt: bigint }],
      'view'
    >
    

    
    maxPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    metadataSigner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    minPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextListingId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextProjectId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    onERC1155BatchReceived: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish[], arg3: BigNumberish[], arg4: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    onERC1155Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BigNumberish, arg4: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    platformFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    projectApprovalQuorum: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    projectEligibleValidatorCount: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    projectTokenizationFees: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, boolean, bigint, bigint] & {lockedFeePerSAL: bigint, depositReceived: bigint, settled: boolean, actualFeeCharged: bigint, refundCredited: bigint }],
      'view'
    >
    

    
    projectValidatorEligible: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    projects: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, boolean, boolean, bigint, boolean, boolean] & {projectId: bigint, owner: string, projectURI: string, proposedCO2Kg: bigint, approvedCO2Kg: bigint, approved: boolean, blacklisted: boolean, createdAt: bigint, exists: boolean, cancelled: boolean }],
      'view'
    >
    

    
    removeValidator: TypedContractMethod<
      [validator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    retireSAL: TypedContractMethod<
      [projectIds: BigNumberish[], salAmounts: BigNumberish[], certificateURI: string, deadline: BigNumberish, metadataSignature: BytesLike, ],
      [void],
      'payable'
    >
    

    
    salToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    salTokenizationFeePerSAL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    sellerBalances: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    submitProject: TypedContractMethod<
      [projectURI: string, proposedCO2Kg: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    tokenizationFeeRefundBalances: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasuryBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unblacklistOwner: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unblacklistProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updateCertificateMintFee: TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateMetadataSigner: TypedContractMethod<
      [newSigner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePlatformFee: TypedContractMethod<
      [newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updatePriceRange: TypedContractMethod<
      [minValue: BigNumberish, maxValue: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateSALTokenizationFeePerSAL: TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    validators: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    voteOnProject: TypedContractMethod<
      [projectId: BigNumberish, approve: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawProceeds: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawTokenizationFeeRefund: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CERTIFICATE_METADATA_TYPEHASH'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'KG_CO2_PER_SAL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_RETIREMENT_PROJECTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addValidator'): TypedContractMethod<
      [validator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveAndMintSAL'): TypedContractMethod<
      [projectId: BigNumberish, approvedCO2Kg: BigNumberish, tokenURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'blacklistOwner'): TypedContractMethod<
      [account: AddressLike, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'blacklistProject'): TypedContractMethod<
      [projectId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'blacklistedOwners'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'buySAL'): TypedContractMethod<
      [listingId: BigNumberish, salAmount: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'cancelListing'): TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelPendingProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'certificateAuthorizationDigest'): TypedContractMethod<
      [retirer: AddressLike, projectIds: BigNumberish[], salAmounts: BigNumberish[], certificateURI: string, nonce: BigNumberish, deadline: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'certificateMintFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'certificateNonces'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'certificateSBT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'claimTreasury'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createListing'): TypedContractMethod<
      [projectId: BigNumberish, amount: BigNumberish, pricePerUnit: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'eip712Domain'): TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'forceCancelListing'): TypedContractMethod<
      [listingId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getProjectValidationSnapshot'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [[bigint, bigint] & {eligibleValidatorCount: bigint, approvalQuorum: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getValidatorsCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hasVotedOnProject'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isValidator'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'listingApprovalVotes'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'listings'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, bigint, bigint, boolean, bigint] & {listingId: bigint, projectId: bigint, seller: string, amount: bigint, pricePerUnit: bigint, active: boolean, createdAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'maxPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'metadataSigner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'minPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextListingId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextProjectId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'onERC1155BatchReceived'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish[], arg3: BigNumberish[], arg4: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'onERC1155Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BigNumberish, arg4: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'platformFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'projectApprovalQuorum'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'projectEligibleValidatorCount'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'projectTokenizationFees'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, boolean, bigint, bigint] & {lockedFeePerSAL: bigint, depositReceived: bigint, settled: boolean, actualFeeCharged: bigint, refundCredited: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'projectValidatorEligible'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'projects'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, boolean, boolean, bigint, boolean, boolean] & {projectId: bigint, owner: string, projectURI: string, proposedCO2Kg: bigint, approvedCO2Kg: bigint, approved: boolean, blacklisted: boolean, createdAt: bigint, exists: boolean, cancelled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'removeValidator'): TypedContractMethod<
      [validator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'retireSAL'): TypedContractMethod<
      [projectIds: BigNumberish[], salAmounts: BigNumberish[], certificateURI: string, deadline: BigNumberish, metadataSignature: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'salToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'salTokenizationFeePerSAL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'sellerBalances'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submitProject'): TypedContractMethod<
      [projectURI: string, proposedCO2Kg: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'tokenizationFeeRefundBalances'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasuryBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unblacklistOwner'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unblacklistProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateCertificateMintFee'): TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateMetadataSigner'): TypedContractMethod<
      [newSigner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePlatformFee'): TypedContractMethod<
      [newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePriceRange'): TypedContractMethod<
      [minValue: BigNumberish, maxValue: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateSALTokenizationFeePerSAL'): TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'validators'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'voteOnProject'): TypedContractMethod<
      [projectId: BigNumberish, approve: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawProceeds'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawTokenizationFeeRefund'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CertificateMintFeeCollected'): TypedContractEvent<CertificateMintFeeCollectedEvent.InputTuple, CertificateMintFeeCollectedEvent.OutputTuple, CertificateMintFeeCollectedEvent.OutputObject>;
getEvent(key: 'CertificateMintFeeUpdated'): TypedContractEvent<CertificateMintFeeUpdatedEvent.InputTuple, CertificateMintFeeUpdatedEvent.OutputTuple, CertificateMintFeeUpdatedEvent.OutputObject>;
getEvent(key: 'EIP712DomainChanged'): TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
getEvent(key: 'ListingCancelled'): TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
getEvent(key: 'ListingCreated'): TypedContractEvent<ListingCreatedEvent.InputTuple, ListingCreatedEvent.OutputTuple, ListingCreatedEvent.OutputObject>;
getEvent(key: 'MetadataSignerUpdated'): TypedContractEvent<MetadataSignerUpdatedEvent.InputTuple, MetadataSignerUpdatedEvent.OutputTuple, MetadataSignerUpdatedEvent.OutputObject>;
getEvent(key: 'MultiProjectSALRetired'): TypedContractEvent<MultiProjectSALRetiredEvent.InputTuple, MultiProjectSALRetiredEvent.OutputTuple, MultiProjectSALRetiredEvent.OutputObject>;
getEvent(key: 'OwnerBlacklisted'): TypedContractEvent<OwnerBlacklistedEvent.InputTuple, OwnerBlacklistedEvent.OutputTuple, OwnerBlacklistedEvent.OutputObject>;
getEvent(key: 'OwnerUnblacklisted'): TypedContractEvent<OwnerUnblacklistedEvent.InputTuple, OwnerUnblacklistedEvent.OutputTuple, OwnerUnblacklistedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PendingProjectCancelled'): TypedContractEvent<PendingProjectCancelledEvent.InputTuple, PendingProjectCancelledEvent.OutputTuple, PendingProjectCancelledEvent.OutputObject>;
getEvent(key: 'ProjectApprovalVoted'): TypedContractEvent<ProjectApprovalVotedEvent.InputTuple, ProjectApprovalVotedEvent.OutputTuple, ProjectApprovalVotedEvent.OutputObject>;
getEvent(key: 'ProjectApproved'): TypedContractEvent<ProjectApprovedEvent.InputTuple, ProjectApprovedEvent.OutputTuple, ProjectApprovedEvent.OutputObject>;
getEvent(key: 'ProjectBlacklisted'): TypedContractEvent<ProjectBlacklistedEvent.InputTuple, ProjectBlacklistedEvent.OutputTuple, ProjectBlacklistedEvent.OutputObject>;
getEvent(key: 'ProjectSubmitted'): TypedContractEvent<ProjectSubmittedEvent.InputTuple, ProjectSubmittedEvent.OutputTuple, ProjectSubmittedEvent.OutputObject>;
getEvent(key: 'ProjectUnblacklisted'): TypedContractEvent<ProjectUnblacklistedEvent.InputTuple, ProjectUnblacklistedEvent.OutputTuple, ProjectUnblacklistedEvent.OutputObject>;
getEvent(key: 'ProjectValidatorSnapshot'): TypedContractEvent<ProjectValidatorSnapshotEvent.InputTuple, ProjectValidatorSnapshotEvent.OutputTuple, ProjectValidatorSnapshotEvent.OutputObject>;
getEvent(key: 'SALPurchased'): TypedContractEvent<SALPurchasedEvent.InputTuple, SALPurchasedEvent.OutputTuple, SALPurchasedEvent.OutputObject>;
getEvent(key: 'SALRetired'): TypedContractEvent<SALRetiredEvent.InputTuple, SALRetiredEvent.OutputTuple, SALRetiredEvent.OutputObject>;
getEvent(key: 'SALTokenizationFeeUpdated'): TypedContractEvent<SALTokenizationFeeUpdatedEvent.InputTuple, SALTokenizationFeeUpdatedEvent.OutputTuple, SALTokenizationFeeUpdatedEvent.OutputObject>;
getEvent(key: 'TokenizationDepositReceived'): TypedContractEvent<TokenizationDepositReceivedEvent.InputTuple, TokenizationDepositReceivedEvent.OutputTuple, TokenizationDepositReceivedEvent.OutputObject>;
getEvent(key: 'TokenizationFeeCollected'): TypedContractEvent<TokenizationFeeCollectedEvent.InputTuple, TokenizationFeeCollectedEvent.OutputTuple, TokenizationFeeCollectedEvent.OutputObject>;
getEvent(key: 'TokenizationFeeRefundCredited'): TypedContractEvent<TokenizationFeeRefundCreditedEvent.InputTuple, TokenizationFeeRefundCreditedEvent.OutputTuple, TokenizationFeeRefundCreditedEvent.OutputObject>;
getEvent(key: 'TokenizationFeeRefundWithdrawn'): TypedContractEvent<TokenizationFeeRefundWithdrawnEvent.InputTuple, TokenizationFeeRefundWithdrawnEvent.OutputTuple, TokenizationFeeRefundWithdrawnEvent.OutputObject>;
getEvent(key: 'TreasuryClaimed'): TypedContractEvent<TreasuryClaimedEvent.InputTuple, TreasuryClaimedEvent.OutputTuple, TreasuryClaimedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'ValidatorAdded'): TypedContractEvent<ValidatorAddedEvent.InputTuple, ValidatorAddedEvent.OutputTuple, ValidatorAddedEvent.OutputObject>;
getEvent(key: 'ValidatorRemoved'): TypedContractEvent<ValidatorRemovedEvent.InputTuple, ValidatorRemovedEvent.OutputTuple, ValidatorRemovedEvent.OutputObject>;

    filters: {
      
      'CertificateMintFeeCollected(address,uint256,uint256,uint256)': TypedContractEvent<CertificateMintFeeCollectedEvent.InputTuple, CertificateMintFeeCollectedEvent.OutputTuple, CertificateMintFeeCollectedEvent.OutputObject>;
      CertificateMintFeeCollected: TypedContractEvent<CertificateMintFeeCollectedEvent.InputTuple, CertificateMintFeeCollectedEvent.OutputTuple, CertificateMintFeeCollectedEvent.OutputObject>;
    

      'CertificateMintFeeUpdated(uint256,uint256)': TypedContractEvent<CertificateMintFeeUpdatedEvent.InputTuple, CertificateMintFeeUpdatedEvent.OutputTuple, CertificateMintFeeUpdatedEvent.OutputObject>;
      CertificateMintFeeUpdated: TypedContractEvent<CertificateMintFeeUpdatedEvent.InputTuple, CertificateMintFeeUpdatedEvent.OutputTuple, CertificateMintFeeUpdatedEvent.OutputObject>;
    

      'EIP712DomainChanged()': TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
      EIP712DomainChanged: TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
    

      'ListingCancelled(uint256)': TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
      ListingCancelled: TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
    

      'ListingCreated(uint256,uint256,address,uint256,uint256)': TypedContractEvent<ListingCreatedEvent.InputTuple, ListingCreatedEvent.OutputTuple, ListingCreatedEvent.OutputObject>;
      ListingCreated: TypedContractEvent<ListingCreatedEvent.InputTuple, ListingCreatedEvent.OutputTuple, ListingCreatedEvent.OutputObject>;
    

      'MetadataSignerUpdated(address,address)': TypedContractEvent<MetadataSignerUpdatedEvent.InputTuple, MetadataSignerUpdatedEvent.OutputTuple, MetadataSignerUpdatedEvent.OutputObject>;
      MetadataSignerUpdated: TypedContractEvent<MetadataSignerUpdatedEvent.InputTuple, MetadataSignerUpdatedEvent.OutputTuple, MetadataSignerUpdatedEvent.OutputObject>;
    

      'MultiProjectSALRetired(address,uint256,uint256[],uint256[],uint256,uint256)': TypedContractEvent<MultiProjectSALRetiredEvent.InputTuple, MultiProjectSALRetiredEvent.OutputTuple, MultiProjectSALRetiredEvent.OutputObject>;
      MultiProjectSALRetired: TypedContractEvent<MultiProjectSALRetiredEvent.InputTuple, MultiProjectSALRetiredEvent.OutputTuple, MultiProjectSALRetiredEvent.OutputObject>;
    

      'OwnerBlacklisted(address,string)': TypedContractEvent<OwnerBlacklistedEvent.InputTuple, OwnerBlacklistedEvent.OutputTuple, OwnerBlacklistedEvent.OutputObject>;
      OwnerBlacklisted: TypedContractEvent<OwnerBlacklistedEvent.InputTuple, OwnerBlacklistedEvent.OutputTuple, OwnerBlacklistedEvent.OutputObject>;
    

      'OwnerUnblacklisted(address)': TypedContractEvent<OwnerUnblacklistedEvent.InputTuple, OwnerUnblacklistedEvent.OutputTuple, OwnerUnblacklistedEvent.OutputObject>;
      OwnerUnblacklisted: TypedContractEvent<OwnerUnblacklistedEvent.InputTuple, OwnerUnblacklistedEvent.OutputTuple, OwnerUnblacklistedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PendingProjectCancelled(uint256,address,uint256)': TypedContractEvent<PendingProjectCancelledEvent.InputTuple, PendingProjectCancelledEvent.OutputTuple, PendingProjectCancelledEvent.OutputObject>;
      PendingProjectCancelled: TypedContractEvent<PendingProjectCancelledEvent.InputTuple, PendingProjectCancelledEvent.OutputTuple, PendingProjectCancelledEvent.OutputObject>;
    

      'ProjectApprovalVoted(uint256,address,bool)': TypedContractEvent<ProjectApprovalVotedEvent.InputTuple, ProjectApprovalVotedEvent.OutputTuple, ProjectApprovalVotedEvent.OutputObject>;
      ProjectApprovalVoted: TypedContractEvent<ProjectApprovalVotedEvent.InputTuple, ProjectApprovalVotedEvent.OutputTuple, ProjectApprovalVotedEvent.OutputObject>;
    

      'ProjectApproved(uint256,address,uint256,uint256)': TypedContractEvent<ProjectApprovedEvent.InputTuple, ProjectApprovedEvent.OutputTuple, ProjectApprovedEvent.OutputObject>;
      ProjectApproved: TypedContractEvent<ProjectApprovedEvent.InputTuple, ProjectApprovedEvent.OutputTuple, ProjectApprovedEvent.OutputObject>;
    

      'ProjectBlacklisted(uint256,string)': TypedContractEvent<ProjectBlacklistedEvent.InputTuple, ProjectBlacklistedEvent.OutputTuple, ProjectBlacklistedEvent.OutputObject>;
      ProjectBlacklisted: TypedContractEvent<ProjectBlacklistedEvent.InputTuple, ProjectBlacklistedEvent.OutputTuple, ProjectBlacklistedEvent.OutputObject>;
    

      'ProjectSubmitted(uint256,address,string,uint256)': TypedContractEvent<ProjectSubmittedEvent.InputTuple, ProjectSubmittedEvent.OutputTuple, ProjectSubmittedEvent.OutputObject>;
      ProjectSubmitted: TypedContractEvent<ProjectSubmittedEvent.InputTuple, ProjectSubmittedEvent.OutputTuple, ProjectSubmittedEvent.OutputObject>;
    

      'ProjectUnblacklisted(uint256)': TypedContractEvent<ProjectUnblacklistedEvent.InputTuple, ProjectUnblacklistedEvent.OutputTuple, ProjectUnblacklistedEvent.OutputObject>;
      ProjectUnblacklisted: TypedContractEvent<ProjectUnblacklistedEvent.InputTuple, ProjectUnblacklistedEvent.OutputTuple, ProjectUnblacklistedEvent.OutputObject>;
    

      'ProjectValidatorSnapshot(uint256,uint256,uint256)': TypedContractEvent<ProjectValidatorSnapshotEvent.InputTuple, ProjectValidatorSnapshotEvent.OutputTuple, ProjectValidatorSnapshotEvent.OutputObject>;
      ProjectValidatorSnapshot: TypedContractEvent<ProjectValidatorSnapshotEvent.InputTuple, ProjectValidatorSnapshotEvent.OutputTuple, ProjectValidatorSnapshotEvent.OutputObject>;
    

      'SALPurchased(uint256,address,uint256,uint256,uint256)': TypedContractEvent<SALPurchasedEvent.InputTuple, SALPurchasedEvent.OutputTuple, SALPurchasedEvent.OutputObject>;
      SALPurchased: TypedContractEvent<SALPurchasedEvent.InputTuple, SALPurchasedEvent.OutputTuple, SALPurchasedEvent.OutputObject>;
    

      'SALRetired(address,uint256,uint256,uint256,uint256)': TypedContractEvent<SALRetiredEvent.InputTuple, SALRetiredEvent.OutputTuple, SALRetiredEvent.OutputObject>;
      SALRetired: TypedContractEvent<SALRetiredEvent.InputTuple, SALRetiredEvent.OutputTuple, SALRetiredEvent.OutputObject>;
    

      'SALTokenizationFeeUpdated(uint256,uint256)': TypedContractEvent<SALTokenizationFeeUpdatedEvent.InputTuple, SALTokenizationFeeUpdatedEvent.OutputTuple, SALTokenizationFeeUpdatedEvent.OutputObject>;
      SALTokenizationFeeUpdated: TypedContractEvent<SALTokenizationFeeUpdatedEvent.InputTuple, SALTokenizationFeeUpdatedEvent.OutputTuple, SALTokenizationFeeUpdatedEvent.OutputObject>;
    

      'TokenizationDepositReceived(uint256,address,uint256,uint256,uint256)': TypedContractEvent<TokenizationDepositReceivedEvent.InputTuple, TokenizationDepositReceivedEvent.OutputTuple, TokenizationDepositReceivedEvent.OutputObject>;
      TokenizationDepositReceived: TypedContractEvent<TokenizationDepositReceivedEvent.InputTuple, TokenizationDepositReceivedEvent.OutputTuple, TokenizationDepositReceivedEvent.OutputObject>;
    

      'TokenizationFeeCollected(uint256,address,uint256,uint256)': TypedContractEvent<TokenizationFeeCollectedEvent.InputTuple, TokenizationFeeCollectedEvent.OutputTuple, TokenizationFeeCollectedEvent.OutputObject>;
      TokenizationFeeCollected: TypedContractEvent<TokenizationFeeCollectedEvent.InputTuple, TokenizationFeeCollectedEvent.OutputTuple, TokenizationFeeCollectedEvent.OutputObject>;
    

      'TokenizationFeeRefundCredited(uint256,address,uint256)': TypedContractEvent<TokenizationFeeRefundCreditedEvent.InputTuple, TokenizationFeeRefundCreditedEvent.OutputTuple, TokenizationFeeRefundCreditedEvent.OutputObject>;
      TokenizationFeeRefundCredited: TypedContractEvent<TokenizationFeeRefundCreditedEvent.InputTuple, TokenizationFeeRefundCreditedEvent.OutputTuple, TokenizationFeeRefundCreditedEvent.OutputObject>;
    

      'TokenizationFeeRefundWithdrawn(address,uint256)': TypedContractEvent<TokenizationFeeRefundWithdrawnEvent.InputTuple, TokenizationFeeRefundWithdrawnEvent.OutputTuple, TokenizationFeeRefundWithdrawnEvent.OutputObject>;
      TokenizationFeeRefundWithdrawn: TypedContractEvent<TokenizationFeeRefundWithdrawnEvent.InputTuple, TokenizationFeeRefundWithdrawnEvent.OutputTuple, TokenizationFeeRefundWithdrawnEvent.OutputObject>;
    

      'TreasuryClaimed(address,uint256)': TypedContractEvent<TreasuryClaimedEvent.InputTuple, TreasuryClaimedEvent.OutputTuple, TreasuryClaimedEvent.OutputObject>;
      TreasuryClaimed: TypedContractEvent<TreasuryClaimedEvent.InputTuple, TreasuryClaimedEvent.OutputTuple, TreasuryClaimedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'ValidatorAdded(address)': TypedContractEvent<ValidatorAddedEvent.InputTuple, ValidatorAddedEvent.OutputTuple, ValidatorAddedEvent.OutputObject>;
      ValidatorAdded: TypedContractEvent<ValidatorAddedEvent.InputTuple, ValidatorAddedEvent.OutputTuple, ValidatorAddedEvent.OutputObject>;
    

      'ValidatorRemoved(address)': TypedContractEvent<ValidatorRemovedEvent.InputTuple, ValidatorRemovedEvent.OutputTuple, ValidatorRemovedEvent.OutputObject>;
      ValidatorRemoved: TypedContractEvent<ValidatorRemovedEvent.InputTuple, ValidatorRemovedEvent.OutputTuple, ValidatorRemovedEvent.OutputObject>;
    
    };
  }