import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'vi' | 'en';

const dictionary: Record<string, { vi: string; en: string }> = {
  'nav.home': { vi: 'Tổng quan', en: 'Overview' },
  'nav.marketplace': { vi: 'Marketplace', en: 'Marketplace' },
  'nav.dashboard': { vi: 'Dashboard', en: 'Dashboard' },
  'nav.retire': { vi: 'Retire', en: 'Retire' },
  'nav.certificates': { vi: 'SBT', en: 'SBT' },
  'nav.leaderboard': { vi: 'Xếp hạng', en: 'Leaderboard' },
  'nav.admin': { vi: 'Admin / Validator', en: 'Admin / Validator' },
  'nav.submit': { vi: 'Đăng ký dự án', en: 'Submit project' },
  'common.connectWallet': { vi: 'Kết nối ví', en: 'Connect wallet' },
  'common.connected': { vi: 'Đã kết nối', en: 'Connected' },
  'common.disconnect': { vi: 'Ngắt kết nối giao diện', en: 'Disconnect UI' },
  'common.cancel': { vi: 'Hủy', en: 'Cancel' },
  'common.close': { vi: 'Đóng', en: 'Close' },
  'common.loading': { vi: 'Đang tải…', en: 'Loading…' },
  'common.processing': { vi: 'Đang xử lý…', en: 'Processing…' },
  'common.project': { vi: 'Dự án', en: 'Project' },
  'common.amount': { vi: 'Số lượng', en: 'Amount' },
  'common.price': { vi: 'Giá', en: 'Price' },
  'common.status': { vi: 'Trạng thái', en: 'Status' },
  'common.date': { vi: 'Ngày', en: 'Date' },
  'common.wallet': { vi: 'Ví', en: 'Wallet' },
  'common.viewTx': { vi: 'Xem giao dịch', en: 'View transaction' },
  'wallet.title': { vi: 'Đăng nhập bằng ví', en: 'Sign in with wallet' },
  'wallet.subtitle': { vi: 'Chọn ví EVM để kết nối với SALX trên Sepolia.', en: 'Choose an EVM wallet to connect to SALX on Sepolia.' },
  'wallet.metamask': { vi: 'MetaMask', en: 'MetaMask' },
  'wallet.coin98': { vi: 'Coin98 Wallet', en: 'Coin98 Wallet' },
  'wallet.browserExtension': { vi: 'Tiện ích trình duyệt', en: 'Browser extension' },
  'wallet.account': { vi: 'Tài khoản đang kết nối', en: 'Connected account' },
  'wallet.network': { vi: 'Mạng', en: 'Network' },
  'wallet.errorInstall': { vi: 'Không tìm thấy ví đã chọn. Hãy cài extension hoặc mở SALX trong dApp browser của ví.', en: 'The selected wallet was not found. Install its extension or open SALX inside the wallet dApp browser.' },
  'home.eyebrow': { vi: 'SALX · Carbon Credit Marketplace', en: 'SALX · Carbon Credit Marketplace' },
  'home.title1': { vi: 'Hạ tầng giao dịch carbon', en: 'Carbon market infrastructure' },
  'home.title2': { vi: 'minh bạch trên blockchain.', en: 'built for transparent on-chain settlement.' },
  'home.desc': { vi: 'Khám phá tín chỉ theo từng dự án, giao dịch SAL với giá minh bạch và retire tối đa 5 nguồn tín chỉ trong một giao dịch để nhận một SBT có audit trail on-chain.', en: 'Discover project-specific credits, trade SAL with transparent project-level pricing, and retire up to five credit sources in one transaction to mint one SBT with an on-chain audit trail.' },
  'home.marketplaceCta': { vi: 'Khám phá Marketplace', en: 'Explore Marketplace' },
  'home.submitCta': { vi: 'Đăng ký dự án', en: 'Submit a project' },
  'home.dashboardCta': { vi: 'Mở Dashboard', en: 'Open Dashboard' },
  'home.approvedProjects': { vi: 'Dự án đã duyệt', en: 'Approved projects' },
  'home.availableCarbon': { vi: 'Carbon đã phê duyệt', en: 'Approved carbon' },
  'home.retiredCarbon': { vi: 'Carbon đã retire', en: 'Retired carbon' },
  'home.salUnit': { vi: 'Đơn vị SAL', en: 'SAL unit' },
  'home.salUnitHint': { vi: 'Là đơn vị carbon, không phải mức giá chung', en: 'A carbon unit, not a universal market price' },
  'home.feature1': { vi: 'Project → SAL', en: 'Project → SAL' },
  'home.feature1d': { vi: 'Backend tạo metadata/IPFS, chủ dự án submit on-chain, validator vote và admin approve để mint ERC-1155 SAL.', en: 'Backend prepares metadata/IPFS, the owner submits on-chain, validators vote, then admin approval mints ERC-1155 SAL.' },
  'home.feature2': { vi: 'SAL → Marketplace', en: 'SAL → Marketplace' },
  'home.feature2d': { vi: 'Mỗi project/listing có giá riêng. 1 SAL luôn đại diện 10 kg CO₂e nhưng không có một mức giá SAL chung.', en: 'Each project/listing has its own price. 1 SAL always represents 10 kg CO₂e, but there is no single SAL market price.' },
  'home.feature3': { vi: 'SAL → SBT', en: 'SAL → SBT' },
  'home.feature3d': { vi: 'Backend ký metadata retirement, smart contract burn SAL và mint Green Certificate SBT.', en: 'Backend signs retirement metadata, then the contract burns SAL and mints a Green Certificate SBT.' },
  'market.eyebrow': { vi: 'Primary marketplace', en: 'Primary marketplace' },
  'market.title': { vi: 'Mua SAL theo từng dự án', en: 'Buy SAL by project' },
  'market.desc': { vi: 'Khám phá nguồn cung SAL theo từng dự án, so sánh giá, phương pháp và địa điểm trước khi mua. Giá vẫn thuộc từng listing, không có một mức giá SAL chung.', en: 'Discover SAL supply by project and compare price, methodology, and location before buying. Pricing remains listing-specific—there is no universal SAL price.' },
  'market.search': { vi: 'Tìm dự án…', en: 'Search projects…' },
  'market.empty': { vi: 'Chưa có listing phù hợp.', en: 'No matching listings yet.' },
  'market.pricePerSal': { vi: 'Giá / SAL', en: 'Price / SAL' },
  'market.remaining': { vi: 'Còn lại', en: 'Remaining' },
  'market.carbonPerSal': { vi: 'Carbon / SAL', en: 'Carbon / SAL' },
  'market.seller': { vi: 'Người bán', en: 'Seller' },
  'market.buyAmount': { vi: 'Số SAL muốn mua', en: 'SAL amount to buy' },
  'market.buy': { vi: 'Mua SAL', en: 'Buy SAL' },
  'market.buying': { vi: 'Đang xác nhận…', en: 'Confirming…' },
  'market.active': { vi: 'Đang bán', en: 'Active' },
  'market.closed': { vi: 'Đã đóng', en: 'Closed' },
  'dashboard.eyebrow': { vi: 'Personal workspace', en: 'Personal workspace' },
  'dashboard.title': { vi: 'Dashboard cá nhân', en: 'Personal dashboard' },
  'dashboard.desc': { vi: 'Không gian cá nhân cho holdings SAL theo từng project, dự án đã submit, listing đang bán, seller proceeds và SBT retirement.', en: 'Your personal workspace for project-specific SAL holdings, submitted projects, active listings, seller proceeds, and retirement SBTs.' },
  'dashboard.notConnected': { vi: 'Kết nối ví để mở dashboard cá nhân.', en: 'Connect a wallet to open your personal dashboard.' },
  'dashboard.totalSal': { vi: 'Tổng SAL đang nắm giữ', en: 'Total SAL holdings' },
  'dashboard.totalCarbon': { vi: 'Carbon tương ứng', en: 'Carbon represented' },
  'dashboard.projects': { vi: 'Dự án của bạn', en: 'Your projects' },
  'dashboard.certificates': { vi: 'SBT đã mint', en: 'Minted SBTs' },
  'dashboard.proceeds': { vi: 'Seller proceeds', en: 'Seller proceeds' },
  'dashboard.proceedsHint': { vi: 'Thu nhập từ listing SAL đã bán', en: 'Earnings from sold SAL listings' },
  'dashboard.refund': { vi: 'Tokenization refund', en: 'Tokenization refund' },
  'dashboard.refundHint': { vi: 'Hoàn phí tokenization khi huỷ project', en: 'Tokenization fee refund on project cancel' },
  'dashboard.mintFee': { vi: 'Phí mint certificate', en: 'Certificate mint fee' },
  'dashboard.holdings': { vi: 'SAL Holdings', en: 'SAL Holdings' },
  'dashboard.holdingsDesc': { vi: 'Số dư được đọc trực tiếp từ ERC-1155 theo projectId.', en: 'Balances are read directly from ERC-1155 by projectId.' },
  'dashboard.pending': { vi: 'Dự án Pending', en: 'Pending projects' },
  'dashboard.listings': { vi: 'Listing của bạn', en: 'Your listings' },
  'dashboard.noListing': { vi: 'Chưa có listing.', en: 'No listings yet.' },
  'dashboard.createListing': { vi: 'Tạo listing', en: 'Create listing' },
  'dashboard.onlyOwner': { vi: 'Theo contract hiện tại, chỉ project owner được tạo listing.', en: 'Under the current contract, only the project owner can create a listing.' },
  'dashboard.pricePerSal': { vi: 'Giá / SAL (ETH)', en: 'Price / SAL (ETH)' },
  'dashboard.listAction': { vi: 'Approve nếu cần & List', en: 'Approve if needed & List' },
  'dashboard.withdraw': { vi: 'Rút', en: 'Withdraw' },
  'dashboard.cancelRefund': { vi: 'Cancel & nhận refund', en: 'Cancel & refund' },
  'dashboard.retireCta': { vi: 'Retire SAL', en: 'Retire SAL' },
  'dashboard.viewCertificates': { vi: 'Xem SBT', en: 'View SBTs' },
  'retire.eyebrow': { vi: 'Retirement flow', en: 'Retirement flow' },
  'retire.title': { vi: 'Retire SAL và mint SBT', en: 'Retire SAL and mint SBT' },
  'retire.desc': { vi: 'Chọn từ 1 đến 5 dự án SAL đang sở hữu, nhập khối lượng cho từng nguồn và retire trong một giao dịch. Backend ký toàn bộ basket, contract burn SAL và mint đúng một SBT.', en: 'Select one to five SAL projects you own, set an amount for each source, and retire them in one transaction. The backend signs the full basket, the contract burns SAL, and exactly one SBT is minted.' },
  'retire.selectProject': { vi: 'Chọn nguồn tín chỉ', en: 'Choose credit source' },
  'retire.balance': { vi: 'Số dư', en: 'Balance' },
  'retire.amount': { vi: 'Số SAL muốn retire', en: 'SAL amount to retire' },
  'retire.summary': { vi: 'Tóm tắt retirement', en: 'Retirement summary' },
  'retire.carbon': { vi: 'Carbon trung hòa', en: 'Carbon retired' },
  'retire.fee': { vi: 'Certificate mint fee', en: 'Certificate mint fee' },
  'retire.action': { vi: 'Retire & Mint SBT', en: 'Retire & Mint SBT' },
  'retire.done': { vi: 'Retirement thành công. SBT sẽ xuất hiện sau khi backend index event.', en: 'Retirement succeeded. The SBT will appear after the backend indexes the event.' },
  'cert.eyebrow': { vi: 'Immutable retirement proof', en: 'Immutable retirement proof' },
  'cert.title': { vi: 'Bằng chứng trung hòa carbon bất biến', en: 'Immutable carbon retirement certificates' },
  'cert.desc': { vi: 'Mặt trước tóm tắt tổng lượng carbon đã retire; mặt sau phân rã 1–5 nguồn dự án theo dữ liệu certificate đã index và có thể xác minh on-chain.', en: 'The front summarizes total retired carbon; the back breaks down one to five project sources from indexed certificate data with on-chain verification.' },
  'cert.none': { vi: 'Bạn chưa có certificate.', en: 'You do not have any certificates yet.' },
  'cert.front': { vi: 'Mặt trước', en: 'Front' },
  'cert.back': { vi: 'Mặt sau', en: 'Back' },
  'cert.totalRetired': { vi: 'Khối lượng trung hòa', en: 'Retired amount' },
  'cert.sourceBreakdown': { vi: 'Phân rã nguồn gốc tín chỉ', en: 'Credit source audit trail' },
  'cert.auditTrail': { vi: 'Phân rã nguồn gốc tín chỉ (Audit Trail)', en: 'Credit source breakdown (Audit Trail)' },
  'cert.verify': { vi: 'Xác minh on-chain', en: 'Verify on-chain' },
  'cert.soulbound': { vi: 'Soulbound Token', en: 'Soulbound Token' },
  'cert.history': { vi: 'Lịch sử giao dịch', en: 'Transaction history' },
  'cert.noHistory': { vi: 'Chưa có giao dịch đã index.', en: 'No indexed transactions yet.' },
  'leader.eyebrow': { vi: 'Impact leaderboard', en: 'Impact leaderboard' },
  'leader.title': { vi: 'Bảng xếp hạng retirement', en: 'Retirement leaderboard' },
  'leader.desc': { vi: 'Xếp hạng địa chỉ ví theo lượng carbon đã retire được backend index.', en: 'Wallets ranked by indexed retired carbon.' },
  'leader.empty': { vi: 'Chưa có dữ liệu retirement.', en: 'No retirement data yet.' },
  'submit.eyebrow': { vi: 'Project owner flow', en: 'Project owner flow' },
  'submit.title': { vi: 'Đăng ký dự án carbon', en: 'Submit a carbon project' },
  'submit.desc': { vi: 'Giữ nguyên flow hiện tại: backend tạo metadata → ví owner gọi submitProject → indexer nhận event.', en: 'Current flow is preserved: backend creates metadata → owner wallet calls submitProject → indexer consumes the event.' },
  'submit.name': { vi: 'Tên dự án', en: 'Project name' },
  'submit.description': { vi: 'Mô tả', en: 'Description' },
  'submit.proposed': { vi: 'Proposed CO₂ (kg)', en: 'Proposed CO₂ (kg)' },
  'submit.type': { vi: 'Loại dự án', en: 'Project type' },
  'submit.location': { vi: 'Địa điểm', en: 'Location' },
  'submit.methodology': { vi: 'Methodology', en: 'Methodology' },
  'submit.start': { vi: 'Monitoring start', en: 'Monitoring start' },
  'submit.end': { vi: 'Monitoring end', en: 'Monitoring end' },
  'submit.external': { vi: 'External URL', en: 'External URL' },
  'submit.image': { vi: 'Image IPFS URI', en: 'Image IPFS URI' },
  'submit.documents': { vi: 'Tài liệu dự án', en: 'Project documents' },
  'submit.requested': { vi: 'SAL dự kiến', en: 'Requested SAL' },
  'submit.action': { vi: 'Tạo metadata & Submit on-chain', en: 'Create metadata & submit on-chain' },
  'submit.connectAction': { vi: 'Kết nối ví để tiếp tục', en: 'Connect wallet to continue' },
  'admin.eyebrow': { vi: 'Demo control panel', en: 'Demo control panel' },
  'admin.title': { vi: 'Admin / Validator', en: 'Admin / Validator' },
  'admin.desc': { vi: 'Giữ nguyên backend hiện tại: validator/admin transaction được ký phía server; frontend chỉ gửi admin secret trong session demo.', en: 'Current backend behavior is preserved: validator/admin transactions are signed server-side; the frontend only sends the demo session admin secret.' },

  'home.retireCta': { vi: 'Retire carbon', en: 'Retire carbon' },
  'home.proofPricing': { vi: 'Giá theo từng dự án', en: 'Project-level pricing' },
  'home.proofProvenance': { vi: 'Nguồn gốc có thể truy vết', en: 'Traceable provenance' },
  'home.proofRetirement': { vi: 'Retirement proof on-chain', en: 'On-chain retirement proof' },
  'home.marketStructureEyebrow': { vi: 'Từ nguồn tín chỉ đến bằng chứng retirement', en: 'From credit source to retirement proof' },
  'home.marketStructureTitle': { vi: 'Một flow rõ ràng cho thị trường carbon on-chain', en: 'A clear flow for an on-chain carbon market' },
  'home.marketStructureDesc': { vi: 'SALX giữ project identity xuyên suốt từ lúc được approve, niêm yết, mua cho đến khi burn và ghi nhận trong SBT.', en: 'SALX preserves project identity from approval and listing through purchase, burn, and final SBT composition.' },
  'home.flowDiscover': { vi: 'Khám phá theo project', en: 'Discover by project' },
  'home.flowDiscoverDesc': { vi: 'Xem loại dự án, địa điểm, methodology, nguồn cung và giá listing trước khi mua SAL.', en: 'Review project type, location, methodology, available supply, and listing price before buying SAL.' },
  'home.flowTrade': { vi: 'Mua SAL minh bạch', en: 'Trade SAL transparently' },
  'home.flowTradeDesc': { vi: 'Mỗi SAL luôn đại diện 10 kg CO₂e nhưng giá phụ thuộc từng project/listing, phản ánh sự khác biệt chất lượng và nguồn cung.', en: 'Each SAL represents 10 kg CO₂e while price remains project/listing-specific, preserving differences in project quality and supply.' },
  'home.flowRetire': { vi: 'Retire 1–5 nguồn → 1 SBT', en: 'Retire 1–5 sources → 1 SBT' },
  'home.flowRetireDesc': { vi: 'Gộp tối đa 5 project trong một retirement basket, burn từng SAL source và nhận một certificate có breakdown nguồn gốc.', en: 'Combine up to five projects in one retirement basket, burn each SAL source, and receive one certificate with a source breakdown.' },
  'home.multiSourceEyebrow': { vi: 'Multi-source retirement', en: 'Multi-source retirement' },
  'home.multiSourceTitle': { vi: 'Một SBT có thể đại diện cho nhiều nguồn tín chỉ', en: 'One SBT can represent multiple credit sources' },
  'home.multiSourceDesc': { vi: 'Thay vì tạo nhiều chứng nhận riêng lẻ, SALX cho phép chọn tối đa 5 project và ghi toàn bộ composition vào cùng một retirement certificate.', en: 'Instead of minting separate certificates, SALX lets you select up to five projects and records the complete composition in a single retirement certificate.' },
  'market.searchLabel': { vi: 'Tìm kiếm', en: 'Search' },
  'market.projectType': { vi: 'Loại dự án', en: 'Project type' },
  'market.allTypes': { vi: 'Tất cả loại dự án', en: 'All project types' },
  'market.sort': { vi: 'Sắp xếp', en: 'Sort by' },
  'market.sortFeatured': { vi: 'Mặc định', en: 'Default' },
  'market.sortPriceAsc': { vi: 'Giá thấp → cao', en: 'Price low → high' },
  'market.sortPriceDesc': { vi: 'Giá cao → thấp', en: 'Price high → low' },
  'market.sortAvailable': { vi: 'Nguồn cung nhiều nhất', en: 'Most available' },
  'market.metadataValid': { vi: 'Metadata hợp lệ', en: 'Metadata valid' },
  'market.carbonAvailable': { vi: 'Carbon khả dụng', en: 'Carbon available' },
  'market.tonneReference': { vi: 'Quy đổi / tCO₂e', en: 'Reference / tCO₂e' },
  'market.buyHint': { vi: 'SAL mua về được giữ trong ví và có thể dùng cho retirement.', en: 'Purchased SAL stays in your wallet and can later be used for retirement.' },
  'market.liveListings': { vi: 'Listing đang mở', en: 'Live listings' },
  'market.projectsAvailable': { vi: 'Dự án có nguồn cung', en: 'Projects with supply' },
  'market.availableSal': { vi: 'SAL khả dụng', en: 'Available SAL' },
  'market.priceRange': { vi: 'Khoảng giá / SAL', en: 'Price range / SAL' },
  'market.discoveryTitle': { vi: 'Khám phá nguồn tín chỉ', en: 'Discover credit sources' },
  'market.discoveryHint': { vi: 'Lọc theo dữ liệu project đã được SALX index; smart contract vẫn là source of truth cho listing và giá.', en: 'Filter by indexed project metadata while the smart contract remains the source of truth for listing supply and price.' },
  'market.emptyHint': { vi: 'Thử thay đổi từ khóa, loại dự án hoặc chờ project owner tạo listing mới.', en: 'Change your search or project type, or wait for project owners to create new listings.' },
  'retire.onChainSource': { vi: 'Nguồn SAL đã approved on-chain', en: 'On-chain approved SAL source' },
  'retire.selectedSources': { vi: 'Nguồn đã chọn', en: 'Selected sources' },
  'retire.totalSal': { vi: 'Tổng SAL burn', en: 'Total SAL to burn' },
  'retire.oneSbtNote': { vi: 'Phí certificate chỉ thu một lần cho cả basket. Tất cả project đã chọn được burn trong cùng giao dịch và mint đúng một SBT.', en: 'The certificate fee is charged once for the basket. All selected projects are burned in the same transaction and exactly one SBT is minted.' },
  'retire.maxReached': { vi: 'Bạn chỉ có thể chọn tối đa {max} dự án trong một lần retire.', en: 'You can select at most {max} projects in one retirement.' },
  'retire.preparingMetadata': { vi: 'Đang tạo metadata và chữ ký cho retirement basket…', en: 'Preparing metadata and signature for the retirement basket…' },
  'retire.confirmWallet': { vi: 'Metadata đã sẵn sàng. Hãy xác nhận giao dịch retire trong ví.', en: 'Metadata is ready. Confirm the retirement transaction in your wallet.' },
  'retire.ruleTitle': { vi: 'Multi-project retirement đang bật', en: 'Multi-project retirement is enabled' },
  'retire.ruleDesc': { vi: 'Mỗi retirement nhận từ 1 đến {max} project và mint một SBT duy nhất.', en: 'Each retirement accepts one to {max} projects and mints a single SBT.' },
  'retire.maxSources': { vi: 'nguồn tối đa', en: 'max sources' },
  'retire.selectHint': { vi: 'Chỉ những project bạn đang có số dư SAL > 0 mới xuất hiện ở đây.', en: 'Only projects where your wallet holds a positive SAL balance appear here.' },
  'retire.noHoldings': { vi: 'Ví chưa có SAL để retire', en: 'No SAL available to retire' },
  'retire.noHoldingsHint': { vi: 'Mua SAL từ Marketplace hoặc dùng ví đang sở hữu SAL trên deployment Sepolia hiện tại.', en: 'Buy SAL from the Marketplace or connect a wallet that holds SAL on the current Sepolia deployment.' },
  'retire.viewSbt': { vi: 'Mở danh sách SBT', en: 'Open SBT collection' },
  'cert.sources': { vi: 'Nguồn tín chỉ', en: 'Credit sources' },
  'cert.holder': { vi: 'Chủ sở hữu', en: 'Holder' },
  'cert.noneHint': { vi: 'Sau khi retire thành công và indexer đồng bộ, certificate sẽ xuất hiện tại đây.', en: 'After a successful retirement and indexer sync, your certificate will appear here.' },
  'cert.historyHint': { vi: 'Các blockchain event liên quan tới ví hiện tại đã được backend index.', en: 'Blockchain events related to the connected wallet as indexed by the backend.' },
  'footer.note': { vi: 'SALX demo frontend · Blockchain là source of truth', en: 'SALX demo frontend · Blockchain is the source of truth' },
};

interface LanguageContextValue {
  language: Language;
  locale: string;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

function initialLanguage(): Language {
  const saved = localStorage.getItem('salx.language');
  if (saved === 'en') return 'en';
  return 'en';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(initialLanguage);

  const setLanguage = (next: Language) => {
    localStorage.setItem('salx.language', next);
    setLanguageState(next);
  };

  useEffect(() => { document.documentElement.lang = language; localStorage.setItem('salx.language', language); }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    locale: language === 'vi' ? 'vi-VN' : 'en-US',
    setLanguage,
    toggleLanguage: () => setLanguage(language === 'vi' ? 'en' : 'vi'),
    t: (key: string) => dictionary[key]?.[language] || key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error('useLanguage must be used inside LanguageProvider');
  return value;
}
